# Generated by Django 5.2.5 on 2025-09-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialization_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa typu wizyty')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Typ wizyty',
                'verbose_name_plural': 'Typy wizyt',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data wizyty')),
                ('time', models.TimeField(verbose_name='Godzina wizyty')),
                ('status', models.CharField(choices=[('scheduled', 'Zaplanowana'), ('canceled', 'Odwołana'), ('completed', 'Zakończona')], default='scheduled', max_length=20, verbose_name='Status wizyty')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Uwagi do wizyty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.doctor', verbose_name='Lekarz')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patient', verbose_name='Pacjent')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.specialization', verbose_name='Specjalizacja')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.appointmenttype', verbose_name='Typ wizyty')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
                'ordering': ['date', 'time'],
            },
        ),
    ]
