# Generated by Django 5.2.5 on 2025-09-23 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appointmenttype_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='Recepta')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Zalecenia')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='accounts.appointment')),
            ],
        ),
    ]
