# Generated by Django 5.2.5 on 2025-10-07 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_visitsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('on_demand', 'Na żądanie'), ('sick_leave', 'Chorobowe')], max_length=20, verbose_name='Typ wolnego')),
                ('start_date', models.DateField(verbose_name='Początek wolnego')),
                ('end_date', models.DateField(verbose_name='Koniec wolnego')),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Załącznik (dla chorobowego)')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na akceptację'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data złożenia wniosku')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.doctor', verbose_name='Lekarz')),
            ],
            options={
                'verbose_name': 'Wniosek o wolne',
                'verbose_name_plural': 'Wnioski o wolne',
                'ordering': ['-created_at'],
            },
        ),
    ]
